-- Daily Jinx: move cumulative scoring out of the browser.
--
-- The service-role daily workflow refreshes only authoritative settlement
-- dates. Each hit is stored once, then a small display-only leaderboard cache
-- is rebuilt for the static frontend.

create table if not exists public.daily_jinx_score_ledger (
  id bigint generated by default as identity primary key,
  vote_id uuid not null references public.daily_jinx_votes(id) on delete cascade,
  account_id uuid not null references auth.users(id) on delete cascade,
  settlement_key text not null,
  vote_date date not null,
  tour text not null check (tour in ('ATP', 'WTA')),
  event_id text not null default '',
  player_name text not null,
  score integer not null check (score > 0),
  match_start_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique (vote_id, settlement_key)
);

create index if not exists daily_jinx_score_ledger_account_idx
  on public.daily_jinx_score_ledger (tour, account_id);

create index if not exists daily_jinx_score_ledger_date_idx
  on public.daily_jinx_score_ledger (vote_date, tour);

create index if not exists daily_jinx_votes_settlement_lookup_idx
  on public.daily_jinx_votes (vote_date, tour, event_id, created_at);

alter table public.daily_jinx_score_ledger enable row level security;
revoke all on public.daily_jinx_score_ledger from public, anon, authenticated;

create table if not exists public.daily_jinx_leaderboard_cache (
  tour text not null check (tour in ('ATP', 'WTA')),
  account_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null,
  score bigint not null default 0,
  hit_count integer not null default 0,
  scored_days integer not null default 0,
  refreshed_at timestamptz not null default now(),
  primary key (tour, account_id)
);

alter table public.daily_jinx_leaderboard_cache enable row level security;
revoke all on public.daily_jinx_leaderboard_cache from public, anon, authenticated;

create or replace function public.daily_jinx_refresh_leaderboard(
  p_settlements jsonb,
  p_refresh_dates date[],
  p_full_refresh boolean default false
)
returns table (
  tour text,
  display_name text,
  score bigint,
  hit_count integer,
  scored_days integer
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if jsonb_typeof(coalesce(p_settlements, '[]'::jsonb)) <> 'array' then
    raise exception 'daily_jinx_settlements_must_be_array';
  end if;

  if not coalesce(p_full_refresh, false)
     and coalesce(array_length(p_refresh_dates, 1), 0) = 0 then
    raise exception 'daily_jinx_refresh_dates_required';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(coalesce(p_settlements, '[]'::jsonb))
      as s(
        vote_date date,
        tour text,
        event_id text,
        match_id text,
        player_name text,
        pick_count integer,
        match_start_at timestamptz
      )
    where s.vote_date is null
       or s.tour not in ('ATP', 'WTA')
       or btrim(coalesce(s.player_name, '')) = ''
       or coalesce(s.pick_count, 0) <= 0
       or s.match_start_at is null
       or (
         coalesce(array_length(p_refresh_dates, 1), 0) > 0
         and not (s.vote_date = any(p_refresh_dates))
       )
  ) then
    raise exception 'daily_jinx_invalid_settlement_payload';
  end if;

  if coalesce(p_full_refresh, false) then
    delete from public.daily_jinx_score_ledger;
  else
    delete from public.daily_jinx_score_ledger
    where vote_date = any(p_refresh_dates);
  end if;

  with settlements as (
    select distinct
      s.vote_date,
      s.tour,
      coalesce(s.event_id, '') as event_id,
      coalesce(s.match_id, '') as match_id,
      btrim(s.player_name) as player_name,
      s.pick_count::integer as pick_count,
      s.match_start_at,
      md5(concat_ws(
        chr(31),
        s.vote_date::text,
        s.tour,
        coalesce(s.event_id, ''),
        coalesce(s.match_id, ''),
        btrim(s.player_name),
        s.match_start_at::text
      )) as settlement_key
    from jsonb_to_recordset(coalesce(p_settlements, '[]'::jsonb))
      as s(
        vote_date date,
        tour text,
        event_id text,
        match_id text,
        player_name text,
        pick_count integer,
        match_start_at timestamptz
      )
  ),
  hits as (
    select distinct
      v.id as vote_id,
      v.account_id,
      s.settlement_key,
      s.vote_date,
      s.tour,
      s.event_id,
      s.player_name,
      s.pick_count as score,
      s.match_start_at
    from settlements s
    join public.daily_jinx_votes v
      on v.vote_date = s.vote_date
     and v.tour = s.tour
     and (s.event_id = '' or s.event_id = coalesce(v.event_id, ''))
     and v.created_at < s.match_start_at
    cross join lateral unnest(v.selected_players) as picked(player_name)
    where btrim(picked.player_name) = s.player_name
  )
  insert into public.daily_jinx_score_ledger (
    vote_id,
    account_id,
    settlement_key,
    vote_date,
    tour,
    event_id,
    player_name,
    score,
    match_start_at
  )
  select
    hit.vote_id,
    hit.account_id,
    hit.settlement_key,
    hit.vote_date,
    hit.tour,
    hit.event_id,
    hit.player_name,
    hit.score,
    hit.match_start_at
  from hits hit
  on conflict (vote_id, settlement_key) do update
  set
    score = excluded.score,
    match_start_at = excluded.match_start_at;

  delete from public.daily_jinx_leaderboard_cache;

  insert into public.daily_jinx_leaderboard_cache (
    tour,
    account_id,
    display_name,
    score,
    hit_count,
    scored_days,
    refreshed_at
  )
  with latest_names as (
    select distinct on (v.account_id)
      v.account_id,
      coalesce(nullif(btrim(v.voter_name_snapshot), ''), '匿名炉友') as display_name
    from public.daily_jinx_votes v
    order by v.account_id, v.created_at desc
  )
  select
    ledger.tour,
    ledger.account_id,
    coalesce(names.display_name, '匿名炉友'),
    sum(ledger.score)::bigint,
    count(*)::integer,
    count(distinct ledger.vote_date)::integer,
    now()
  from public.daily_jinx_score_ledger ledger
  left join latest_names names on names.account_id = ledger.account_id
  group by ledger.tour, ledger.account_id, names.display_name;

  return query
  select
    cache.tour,
    cache.display_name,
    cache.score,
    cache.hit_count,
    cache.scored_days
  from public.daily_jinx_leaderboard_cache cache
  order by
    cache.tour,
    cache.score desc,
    cache.hit_count desc,
    cache.display_name asc;
end;
$$;

revoke all on function public.daily_jinx_refresh_leaderboard(jsonb, date[], boolean)
  from public, anon, authenticated;
grant execute on function public.daily_jinx_refresh_leaderboard(jsonb, date[], boolean)
  to service_role;
